### ISSUE TITLE
Doesn't compile with TS 4.4.0 beta

### ISSUE THREAD

**Issue by e-oz** [georgipeltekov/ngx-file-drop#236]
TypeScript 4.4.0 beta gives this log, please take a look:
```
node_modules/ngx-file-drop/ngx-file-drop/dom.types.d.ts:11:95 - error TS2304: Cannot find name 'DOMError'.

11     readEntries(successCallback: (result: FileSystemEntry[]) => void, errorCallback?: (error: DOMError) => void): void;
                                                                                                 ~~~~~~~~
node_modules/ngx-file-drop/ngx-file-drop/dom.types.d.ts:21:136 - error TS2304: Cannot find name 'DOMError'.

21     getFile(path?: string, options?: FileSystemFlags, successCallback?: (result: FileSystemFileEntry) => void, errorCallback?: (error: DOMError) => void): void;
                                                                                                                                          ~~~~~~~~
node_modules/ngx-file-drop/ngx-file-drop/dom.types.d.ts:22:146 - error TS2304: Cannot find name 'DOMError'.

22     getDirectory(path?: string, options?: FileSystemFlags, successCallback?: (result: FileSystemDirectoryEntry) => void, errorCallback?: (error: DOMError) => void): void;
                                                                                                                                                    ~~~~~~~~
```

**Comment by e-oz** [comment]
ngx-file-drop version: 11.1.0

**Comment by CrackerakiUA** [comment]
I do have the same issue, any temporary fix for this?

**Comment by CrackerakiUA** [comment]
I made a temporary package, which will be removed after issue will be solved. https://www.npmjs.com/package/ngx-file-drop-temp

**Comment by georgipeltekov** [comment]
@CrackerakiUA  if you create a pull request with the needed changes I will merge and publish them

**Comment by CrackerakiUA** [comment]
I just replaced `DOMError` with `any`. Don't feel like that is proper change.

**Comment by tomwillwerth** [comment]
Angular 13 is published and this error prevents updating to 13 since it uses Typescript 4.4.x.

I think DOMError can be replaced with DOMException and it will fix the issue.

**Comment by georgipeltekov** [comment]
it should be ok with 11.3.0

**Comment by vijaypatoliya** [comment]
npm install ngx-file-drop@13.0.0 --save --force

This work for me , we have use latest version with angular
