### ISSUE TITLE
Error after upgrade app to angular 6

### ISSUE THREAD

**Issue by chrisbenseler** [georgipeltekov/ngx-file-drop#61]
After upgrade an app to latest angular, 6, the build started to output:

node_modules/ngx-file-drop/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'

**Comment by alfonsserra** [comment]
Same error here. As I can see in package.json, Angular 6 is not supported yet. Any plans to update?

**Comment by swftvsn** [comment]
Opened PR #62 to fix this.

**Comment by georgipeltekov** [comment]
fixed in 4.0.0

**Comment by chrisbenseler** [comment]
Thanks @georgipeltekov it's working now!

**Comment by georgipeltekov** [comment]
all the thanks are for @swftvsn

**Comment by swftvsn** [comment]
Thanks @georgipeltekov! Your response time is excellent and awesome job for the library!

**Comment by DanielRyan** [comment]
I am still having this issue with v4.0.0 :/
Repro steps:

- Create new angular 6 project
- npm install ngx-file-drop
- Import ngx-file-drop somewhere in the project
- Run ng serve

On ng serve I get this error message:

> ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
> node_modules/ngx-file-drop/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by georgipeltekov** [comment]
Can you create reproducible stackblitz example . As you can see here : https://stackblitz.com/edit/angular-k4emfw
it works fine with angular 6 and version 4.0.0

**Comment by PLPeeters** [comment]
I'm getting the same issue as @DanielRyan. Removing the `node_modules` folder inside `node_modules/ngx-file-drop` fixes the issue for me.

**Comment by georgipeltekov** [comment]
@PLPeeters  thanks for the solution.

**Comment by PLPeeters** [comment]
We definitely need a more durable solution to this.

**Comment by jdell64** [comment]
Submitted a PR, under the uneducated guess that the trailing slash in the gitignore needs to be there:

https://github.com/georgipeltekov/ngx-file-drop/pull/68

**Comment by jdell64** [comment]
temporary workaround: 

`"postinstall": "rm -rf node_modules/ngx-file_drop/node_modules"`

**Comment by PLPeeters** [comment]
The trailing slash shouldn't change anything, and I don't believe the `.gitignore` impacts the build in any way, unless I misunderstood something.

Thanks for the `package.json` workaround though!

**Comment by jdell64** [comment]
I didn't think so either, but from what I read, "directories need that trailing slash," and "in the absence of an npmignore file, it uses the gitignore file." Again, just my uneducated guess, and I think its wrong. Don't have a good fix :/

**Comment by PLPeeters** [comment]
@jdell64 Directories don't really need the trailing slash (for `.gitignore` files anyway). The difference between putting `npm_modules` and `npm_modules/` in a `.gitignore` file is that the former will match _both_ files and folders named `npm_modules`, while the latter will only match folders.

I just though of something though. I have no experience in the development of Node packages, but from what I'm seeing in other packages and in the documentation, I believe all the packages that are under the `dependencies` key should be under `peerDependencies` instead, which would fix this issue (@georgipeltekov).

**Comment by PLPeeters** [comment]
Looks like doing that breaks the CI build, but I'm wondering if that couldn't just be because the CI build script needs to be updated due to these changes.

**Comment by georgipeltekov** [comment]
Hey @PLPeeters  thanks for your input. Unfortunately as you noticed this is breaking the build. The script is quite straightforward and it is something that the users will do once they downloaded the app. As far as I see it breaks on npm install 
https://travis-ci.org/georgipeltekov/ngx-file-drop/jobs/379215367

**Comment by PLPeeters** [comment]
It breaks on `npm install` because it's complaining that it doesn't have `@angular/core`, etc. which the user need to have if they are going to install and use this package anyway.

The normal installation procedure would be:

* `ng new app`, which will install all the required `@angular/*` modules, `rxjs`, etc.
* Installing `ngx-file-drop`, for which the peer-dependencies will be satisfied by the previous step.

**Comment by georgipeltekov** [comment]
I tried to test the peerDependencies changes and not breaking the builds, but failed to succeed. Also the packagr complains about that. I will try to find time tomorrow to check it again.

**Comment by AndreasSchmid1** [comment]
this issue still exists for angular 6. removing the node modules is still a valid workaround, but kinda messy. any updates on this?

**Comment by georgipeltekov** [comment]
@AndreasSchmid1  what version are you using?

**Comment by AndreasSchmid1** [comment]
@georgipeltekov i tried 2.0.5 and 5.0.0

**Comment by georgipeltekov** [comment]
and with what angular version?
if you are using Angular 6, you should tried 4.0.4, based on my comment above. 5.0.0 is for  Angular 7.

**Comment by AndreasSchmid1** [comment]
thx man! I kind of completely missed it.
