### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by twalk4821** [georgipeltekov/ngx-file-drop#75]
I was hoping to utilize this module, but I am encountering an error whenever I try to drop a file. The other handlers, fileOver and fileLeave, work fine. But when I drop the file, I get:
```
FileComponent.html:1 ERROR TypeError: Object(...) is not a function
```
I am following the example exactly for now. I am using Angular version 5. Thanks!

**Comment by twalk4821** [comment]
Hm, just tried with version 3.0.2 and no luck. 

On  stackblitz I'm getting a different error...

https://angular-rvxumz.stackblitz.io
![screen shot 2018-05-25 at 12 19 08 am](https://user-images.githubusercontent.com/23714337/40531444-50a0fa8c-5fb1-11e8-9d0e-0f075a0f5442.png)

**Comment by georgipeltekov** [comment]
In the stackblitz example you are using version 4.0.4 of the library. Also the error you are displaying is because you are trying to use console.log in the template. If you change it in this way:
(onFileDrop)="fileDropped($event)"

and after that in the function in the function you have:
public fileDropped(event: UploadEvent) {
      console.log(event)
}

you are good to go.

**Comment by twalk4821** [comment]
![screen shot 2018-05-25 at 1 00 52 am](https://user-images.githubusercontent.com/23714337/40533306-29eeb9e6-5fb7-11e8-9f55-a2eb485d4df0.png)

I also got an error about rxjs.timer not being a function.

I guess I really need to be in Angular 6.

**Comment by twalk4821** [comment]
sorry different stackblitz now:
https://stackblitz.com/edit/angular-5-tutorial?file=app%2Fapp.component.html

**Comment by georgipeltekov** [comment]
this stackblitz is working with angular 5 and 3.0.2
https://stackblitz.com/edit/angular-awlfv4

(check the versions of angular core and rjx)

**Comment by twalk4821** [comment]
Unfortunately, same error. I'll let you know if I'm able to resolve this.

**Comment by georgipeltekov** [comment]
Please checkthe stackblitz I provided an compare the versions.  Also delete the node_modules folder inside the ngx-file-drop package and run npm install after that.

**Comment by twalk4821** [comment]
Yes that last step seemed to do it, thank you.

**Comment by jponcelin** [comment]
Hello everyone, 
Just had the same issue.
I'm working on an angular 5 project, can't upgrade.
Passing on a 3.0.2 did the trick, but is there a way to keep the browseBtnLabel and showBrowseBtn ?
I could really use that.

**Comment by georgipeltekov** [comment]
Hi @jponcelin ,

unfortunately this new features are only supported in the latest version

**Comment by jponcelin** [comment]
Thank you for your quick answer, I asked but I had low hope ^^.
If someone is having the same issue, I added a button that I linked to an input type file like this : 
http://jsfiddle.net/gregorypratt/dhyzV/

Now I've to make sure the component and the input work together...

Is it possible on the file-drop component (3.0.2) to say what kind of files we want to accept ?
And to drop only one file at the time ?

Thank you.

**Comment by georgipeltekov** [comment]
you can add this logic, once the files are dropped i.e if their count is > 1 to display some message or check their filetypes . you can check also #83
